# IDAPython Export Script - Generated by DissectX
# This script exports IDA Pro analysis data to JSON format
#
# Usage: File -> Script file... -> Select this script
# The script will create a JSON file in the same directory as the IDB

import json
import ida_bytes
import ida_funcs
import ida_name
import ida_segment
import ida_struct
import ida_enum
import ida_xref
import idaapi
import idc
from pathlib import Path

def export_ida_to_json():
    """Export IDA Pro analysis to JSON format"""
    
    data = {
        'database': {
            'name': idc.get_root_filename(),
            'base_address': hex(idaapi.get_imagebase()),
            'bitness': 64 if idaapi.get_inf_structure().is_64bit() else 32,
            'processor': idaapi.get_inf_structure().procname
        },
        'segments': [],
        'functions': [],
        'names': [],
        'comments': [],
        'xrefs': [],
        'structs': [],
        'enums': []
    }
    
    # Export segments
    print('Exporting segments...')
    for seg_ea in idautils.Segments():
        seg = idaapi.getseg(seg_ea)
        data['segments'].append({
            'name': idc.get_segm_name(seg_ea),
            'start_address': hex(seg.start_ea),
            'end_address': hex(seg.end_ea),
            'type': 'CODE' if seg.type == idaapi.SEG_CODE else 'DATA',
            'permissions': 'rwx',  # Simplified
            'bitness': data['database']['bitness']
        })
    
    # Export functions
    print('Exporting functions...')
    for func_ea in idautils.Functions():
        func = ida_funcs.get_func(func_ea)
        data['functions'].append({
            'address': hex(func_ea),
            'name': idc.get_func_name(func_ea),
            'end_address': hex(func.end_ea) if func else None,
            'comment': idc.get_func_cmt(func_ea, 0),
            'repeatable_comment': idc.get_func_cmt(func_ea, 1)
        })
    
    # Export names
    print('Exporting names...')
    for name_ea, name in idautils.Names():
        data['names'].append({
            'address': hex(name_ea),
            'name': name,
            'is_code': idc.is_code(idc.get_full_flags(name_ea)),
            'is_data': idc.is_data(idc.get_full_flags(name_ea))
        })
    
    # Export comments
    print('Exporting comments...')
    for func_ea in idautils.Functions():
        func = ida_funcs.get_func(func_ea)
        if func:
            for ea in range(func.start_ea, func.end_ea):
                cmt = idc.get_cmt(ea, 0)
                if cmt:
                    data['comments'].append({
                        'address': hex(ea),
                        'type': 'regular',
                        'text': cmt
                    })
    
    # Write to JSON file
    idb_path = idc.get_idb_path()
    json_path = Path(idb_path).with_suffix('.json')
    
    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2)
    
    print(f'Export complete: {json_path}')
    return str(json_path)

# Run the export
if __name__ == '__main__':
    import idautils
    output_file = export_ida_to_json()
    print(f'IDA data exported to: {output_file}')