#!/usr/bin/env python3
# Generated by DissectX ROPAnalyzer
from pwn import *

# Binary: ls
# Architecture: x64
# Total gadgets: 310

# ROP Gadgets

# CONTROL gadgets
control_100002e87 = 0x100002e87  # add byte ptr [rax + 0xf], cl ; ret 0xd8b
control_10000383c = 0x10000383c  # add byte ptr [rax + rax + 0x1e07d011], al ; retf 0x50
control_100000a02 = 0x100000a02  # add byte ptr [rax + riz*2 - 0x5c4bfffc], dl ; ret
control_100000fc2 = 0x100000fc2  # add byte ptr [rax - 0x46ffcee1], dl ; retf 0xfffe
control_10000425a = 0x10000425a  # add byte ptr [rax - 0x6ed4839d], dl ; ret 0x8011
control_100001657 = 0x100001657  # add byte ptr [rax - 0x77], cl ; ret
control_100002657 = 0x100002657  # add byte ptr [rax - 0x77], cl ; ret 0xc031
control_100001a6a = 0x100001a6a  # add byte ptr [rax - 1], cl ; ret
control_100000b25 = 0x100000b25  # add byte ptr [rax], al ; jmp 0x100000af4
control_100000ade = 0x100000ade  # add byte ptr [rbp + rcx*4 + 0x3d], cl ; retf

# Example ROP chain
rop = ROP(elf)
# Add your gadgets here
# rop.raw(gadget_address)
